### ISSUE TITLE
Request for macOS GPU Support

### ISSUE THREAD

**Issue by manwallet** [FLock-io/llm-loss-validator#46]
Hello,

I am currently using your software on macOS with the Apple M1 Ultra. However, I have noticed that the GPU performance on macOS is not being fully utilized, which significantly impacts overall efficiency.

Additionally, the unified memory architecture on Mac has a significant advantage when handling large datasets. If GPU resources could be fully leveraged, I believe performance would see a substantial improvement.

I hope you can consider adding support for macOS GPUs. Thank you for your hard work!

**Comment by manwallet** [comment]
(llm-loss-validator) beluga@belugadeMac-Studio src % bash start.sh \
--hf_token hf_api \
--flock_api_key My api \
--task_id 9 \
--validation_args_file validation_config.json.example \
--auto_clean_cache False \
--lora_only True
2024-08-13 17:40:17.268 | INFO     | __main__:loop:403 - Skip auto clean the model cache
2024-08-13 17:40:18.578 | INFO     | __main__:loop:417 - Validating task_id: ['9']
2024-08-13 17:40:21.036 | INFO     | __main__:download_file:82 - Downloaded the file to /var/folders/1k/3jlkl2j90fs1snh1vql696p40000gn/T/tmpxpmr2gir
2024-08-13 17:40:22.002 | INFO     | __main__:load_tokenizer:110 - vocab_size of tokenizer: 151643
2024-08-13 17:40:22.002 | INFO     | __main__:load_sft_dataset:207 - Loading data with UnifiedSFTDataset
2024-08-13 17:40:22.002 | INFO     | core.dataset:__init__:17 - Loading data: /var/folders/1k/3jlkl2j90fs1snh1vql696p40000gn/T/tmpxpmr2gir
2024-08-13 17:40:22.003 | INFO     | core.dataset:__init__:20 - Use template "qwen1.5" for training
2024-08-13 17:40:22.003 | INFO     | core.dataset:__init__:21 - There are 200 data in dataset
2024-08-13 17:40:22.003 | INFO     | __main__:load_model:117 - Loading model from base model: brandonshit/Qwen-Qwen1.5-7B-1723028178
adapter_config.json: 100%|██████████████████████████████████████████████| 638/638 [00:00<00:00, 1.13MB/s]
2024-08-13 17:40:22.632 | INFO     | __main__:load_model:131 - Repo is a lora weight, loading model with adapter weights
Loading checkpoint shards: 100%|███████████████████████████████████████████| 4/4 [00:07<00:00,  1.80s/it]
README.md: 100%|█████████████████████████████████████████████████████| 5.09k/5.09k [00:00<00:00, 508kB/s]
.gitattributes: 100%|███████████████████████████████████████████████| 1.52k/1.52k [00:00<00:00, 10.2MB/s]
training_args.bin: 100%|████████████████████████████████████████████| 5.30k/5.30k [00:00<00:00, 7.94MB/s]
adapter_model.safetensors: 100%|████████████████████████████████████| 8.41M/8.41M [00:01<00:00, 6.20MB/s]
Fetching 11 files: 100%|█████████████████████████████████████████████████| 11/11 [00:03<00:00,  2.91it/s]
2024-08-13 17:40:45.802 | INFO     | __main__:load_model:146 - Loaded model with adapter weights
2024-08-13 17:40:45.803 | INFO     | __main__:load_model:162 - memory footprint of model: 14.882095336914062 GB
2024-08-13 17:40:45.803 | INFO     | __main__:load_model:167 - Total model params: 7721.32M
2024-08-13 17:40:45.848 | DEBUG    | __main__:validate:358 - Offloading model to save memory
2024-08-13 17:40:45.849 | DEBUG    | __main__:validate:362 - Offloading eval_dataset to save memory
2024-08-13 17:40:45.850 | DEBUG    | __main__:validate:367 - Removing lora folder
2024-08-13 17:40:45.858 | ERROR    | core.exception:handle_value_error:48 - Unknown ValueError detected, exiting with code 100, will restart... fp16 mixed precision requires a GPU (not 'mps').
CUDA error detected, restarting the process...
2024-08-13 17:40:48.180 | INFO     | __main__:loop:403 - Skip auto clean the model cache
2024-08-13 17:40:49.434 | INFO     | __main__:loop:417 - Validating task_id: ['9']
Traceback (most recent call last):
  File "/Users/beluga/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/Users/beluga/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/Users/beluga/.local/lib/python3.10/site-packages/urllib3/connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/Users/beluga/.local/lib/python3.10/site-packages/urllib3/connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/Users/beluga/.local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/Users/beluga/.local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/anaconda3/envs/llm-loss-validator/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/anaconda3/envs/llm-loss-validator/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/opt/anaconda3/envs/llm-loss-validator/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/beluga/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/Users/beluga/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:997)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/beluga/.local/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/Users/beluga/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/Users/beluga/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='fed-ledger-prod.flock.io', port=443): Max retries exceeded with url: /api/v1/tasks/request-validation-assignment/9 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/beluga/llm-loss-validator/src/validate.py", line 493, in <module>
    cli()
  File "/Users/beluga/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/beluga/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/beluga/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/beluga/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/beluga/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/beluga/llm-loss-validator/src/validate.py", line 423, in loop
    resp = fed_ledger.request_validation_assignment(task_id_num)
  File "/Users/beluga/llm-loss-validator/src/client/fed_ledger.py", line 17, in request_validation_assignment
    response = requests.post(url, headers=self.headers)
  File "/Users/beluga/.local/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Users/beluga/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/beluga/.local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/beluga/.local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/beluga/.local/lib/python3.10/site-packages/requests/adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='fed-ledger-prod.flock.io', port=443): Max retries exceeded with url: /api/v1/tasks/request-validation-assignment/9 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
Validation failed with exit code 1
(llm-loss-validator) beluga@belugadeMac-Studio src %

**Comment by mizandon** [comment]
Flock-ai not verified issu
